# Generated by Django 4.2.7 on 2023-12-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=250)),
                ('recept', models.CharField(max_length=500)),
                ('usage', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('last_update', models.DateField(auto_now=True)),
                ('link', models.CharField(editable=False, max_length=255, unique=True)),
                ('type_of_med', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.type_of_med')),
            ],
        ),
    ]
