# Generated by Django 4.2.7 on 2023-12-12 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_confirmationcode_customusers_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
